### ISSUE TITLE
博客文章翻译任务认领

### ISSUE THREAD

**Issue by KimYangOfCat** [docschina/babeljs-cn#102]
## 翻译任务认领说明
翻译前，请仔细阅读 [中文文档译文排版指南](https://github.com/reactjs/zh-hans.reactjs.org/wiki/React-%E4%B8%AD%E6%96%87%E6%96%87%E6%A1%A3%E8%AF%91%E6%96%87%E6%8E%92%E7%89%88%E6%8C%87%E5%8D%97)
>  注意：一次尽量只认领一篇，给其他小伙伴留些机会～

从 Todo List 中选取未被人领取过得文章：

未被领取过：
- [ ] Home Page

领取过但尚未完成：
- [ ] Home Page(@KimYangOfCat )

领取过并已完成：
- [x] Home Page(@KimYangOfCat )#55

认领方式，在本 issues 下评论即可。

认领任务格式：
```
Section | Title | 译者 | 完成时间 | PR
-- | -- | -- | --
Blog |  6to5 + esnext | @KimYangOfCat  | 2021.05.1 - 2021.05.07 | -
```
示列效果：
Section | Title | 译者 | 完成时间 | PR
-- | -- | -- | -- | --
Blog |  6to5 + esnext | @KimYangOfCat  | 2021.05.1 - 2021.05.07 | -

完成翻译时，请将 PR 填入表格：
Section | Title | 译者 | 完成时间 | PR
-- | -- | -- | -- | -- 
Blog |  6to5 + esnext | @KimYangOfCat  | 2021.05.1 - 2021.05.07 | #55

### Blog

- [x] [7.16.0 Released: ESLint 8 and TypeScript 4.5](https://github.com/docschina/babeljs-cn/blob/ecf0773222f2d046ddc7bbdae6e825beb823d1b9/website/blog/2021-10-29-7.16.0.md)(@htmlin )#121
- [x] [7.15.0 Released: Hack-style pipelines, TypeScript const enums and Rhino target support](https://github.com/docschina/babeljs-cn/blob/cn-v7/website/blog/2021-07-26-7.15.0.md)(@htmlin )#112
- [ ] [Babel is used by millions, so why are we running out of money?](https://github.com/docschina/babeljs-cn/blob/cn-v7/website/blog/2021-05-10-funding-update.md)
- [ ] [7.14.0 Released: New class features enabled by default, TypeScript 4.3, and better CommonJS interop](https://github.com/docschina/babeljs-cn/blob/cn-v7/website/blog/2021-02-22-7.13.0.md)
- [ ] [7.13.0 Released: Records and Tuples, granular compiler assumptions, and top-level targets](https://github.com/docschina/babeljs.cn/tree/cn-v7/website/blog/2021-02-22-7.13.0.md)
- [x] [6to5 + esnext](https://github.com/docschina/babeljs.cn/tree/cn-v7/website/blog/2015-01-12-6to5-esnext.md)
- [x] [2to3](https://github.com/docschina/babeljs.cn/tree/cn-v7/website/blog/2015-01-27-2to3.md)
- [x] [并非出生而逐渐走向灭亡](https://github.com/docschina/babeljs.cn/tree/cn-v7/website/blog/2015-02-15-not-born-to-die.md)
- [x] [Babel 喜爱 React](https://github.com/docschina/babeljs.cn/tree/cn-v7/website/blog/2015-02-23-babel-loves-react.md)
- [ ] [5.0.0 Released](https://github.com/docschina/babeljs.cn/tree/cn-v7/website/blog/2015-03-31-5.0.0.md)
- [ ] [Function Bind Syntax](https://github.com/docschina/babeljs.cn/tree/cn-v7/website/blog/2015-05-14-function-bind.md)
- [ ] [React on ES6+](https://github.com/docschina/babeljs.cn/tree/cn-v7/website/blog/2015-07-07-react-on-es6-plus.md)
- [ ] [6.0.0 Released](https://github.com/docschina/babeljs.cn/tree/cn-v7/website/blog/2015-10-29-6.0.0.md)
- [ ] [Setting up Babel 6](https://github.com/docschina/babeljs.cn/tree/cn-v7/website/blog/2015-10-31-setting-up-babel-6.md)
- [ ] [Babel Doctor](https://github.com/docschina/babeljs.cn/tree/cn-v7/website/blog/2015-11-03-babel-doctor.md)
- [ ] [6.14.0 Released](https://github.com/docschina/babeljs.cn/tree/cn-v7/website/blog/2016-08-24-6.14.0.md)
- [ ] [Babili (babel-minify)](https://github.com/docschina/babeljs.cn/tree/cn-v7/website/blog/2016-08-26-babili.md)
- [ ] [6.16.0 Released](https://github.com/docschina/babeljs.cn/tree/cn-v7/website/blog/2016-09-28-6.16.0.md)
- [ ] [6.18.0 Released](https://github.com/docschina/babeljs.cn/tree/cn-v7/website/blog/2016-10-24-6.18.0.md)
- [ ] [6.19.0 Released](https://github.com/docschina/babeljs.cn/tree/cn-v7/website/blog/2016-11-16-6.19.0.md)
- [ ] [The State of Babel](https://github.com/docschina/babeljs.cn/tree/cn-v7/website/blog/2016-12-07-the-state-of-babel.md)
- [ ] [6.23.0 Released](https://github.com/docschina/babeljs.cn/tree/cn-v7/website/blog/2017-02-13-6.23.0.md)
- [ ] [Upgrade to Babel 7 for Tool Authors (WIP)](https://github.com/docschina/babeljs.cn/tree/cn-v7/website/blog/2017-03-01-upgrade-to-babel-7-for-tool-authors.md)
- [ ] [Upgrade to Babel 7 (moved)](https://github.com/docschina/babeljs.cn/tree/cn-v7/website/blog/2017-03-01-upgrade-to-babel-7.md)
- [ ] [Babel and Summer of Code 2017](https://github.com/docschina/babeljs.cn/tree/cn-v7/website/blog/2017-08-09-babel-and-summer-of-code.md)
- [ ] [Personal Experiences at Babel #1 — A PR with Unusually High Number of Reviews](https://github.com/docschina/babeljs.cn/tree/cn-v7/website/blog/2017-08-11-gsoc-peey-1.md)
- [ ] [Contributing to Babel: Three Lessons to Remember](https://github.com/docschina/babeljs.cn/tree/cn-v7/website/blog/2017-08-16-gsoc-karl-1.md)
- [ ] [Zero-config code transformation with babel-plugin-macros](https://github.com/docschina/babeljs.cn/tree/cn-v7/website/blog/2017-09-11-zero-config-with-babel-macros.md)
- [ ] [Planning for 7.0](https://github.com/docschina/babeljs.cn/tree/cn-v7/website/blog/2017-09-12-planning-for-7.0.md)
- [ ] [Babel Turns Three](https://github.com/docschina/babeljs.cn/tree/cn-v7/website/blog/2017-10-05-babel-turns-three.md)
- [ ] [Nearing the 7.0 Release](https://github.com/docschina/babeljs.cn/tree/cn-v7/website/blog/2017-12-27-nearing-the-7.0-release.md)
- [ ] [On Consuming (and Publishing) ES2015+ Packages](https://github.com/docschina/babeljs.cn/tree/cn-v7/website/blog/2018-06-26-on-consuming-and-publishing-es2015+-packages.md)
- [ ] [Announcing Babel's New Partnership with trivago!](https://github.com/docschina/babeljs.cn/tree/cn-v7/website/blog/2018-07-16-announcing-babels-new-partnership-with-trivago.md)
- [ ] [What's Happening With the Pipeline (|>) Proposal?](https://github.com/docschina/babeljs.cn/tree/cn-v7/website/blog/2018-07-19-whats-happening-with-the-pipeline-proposal.md)
- [ ] [Removing Babel's Stage Presets](https://github.com/docschina/babeljs.cn/tree/cn-v7/website/blog/2018-07-27-removing-babels-stage-presets.md)
- [x] [Babel 7 发布](https://github.com/docschina/babeljs.cn/tree/cn-v7/website/blog/2018-08-27-7.0.0.md)
- [ ] [7.1.0 Released: Decorators, Private Static Fields](https://github.com/docschina/babeljs.cn/tree/cn-v7/website/blog/2018-09-17-7.1.0.md)
- [x] [在 Babel 中支持 TC39 标准的装饰器](https://github.com/docschina/babeljs.cn/tree/cn-v7/website/blog/2018-09-17-decorators.md)
- [x] [7.2.0 发布：私有实例方法（Private Instance Methods）](https://github.com/docschina/babeljs.cn/tree/cn-v7/website/blog/2018-12-03-7.2.0.md)
- [x] [7.3.0 Released: Named capturing groups, private instance accessors and smart pipelines](https://github.com/docschina/babeljs.cn/tree/cn-v7/website/blog/2019-01-21-7.3.0.md)
- [ ] [7.4.0 Released: core-js 3, static private methods and partial application](https://github.com/docschina/babeljs.cn/tree/cn-v7/website/blog/2019-03-19-7.4.0.md)
- [ ] [The Babel Podcast](https://github.com/docschina/babeljs.cn/tree/cn-v7/website/blog/2019-07-02-the-babel-podcast.md)
- [ ] [7.5.0 Released: dynamic import and F# pipelines](https://github.com/docschina/babeljs.cn/tree/cn-v7/website/blog/2019-07-03-7.5.0.md)
- [ ] [7.6.0 Released: Private static accessors and V8 intrinsic syntax](https://github.com/docschina/babeljs.cn/tree/cn-v7/website/blog/2019-09-05-7.6.0.md)
- [ ] [7.7.0 Released: Error recovery and TypeScript 3.7](https://github.com/docschina/babeljs.cn/tree/cn-v7/website/blog/2019-11-05-7.7.0.md)
- [ ] [Babel's Funding Plans](https://github.com/docschina/babeljs.cn/tree/cn-v7/website/blog/2019-11-08-babels-funding-plans.md)
- [ ] [7.8.0 Released: ECMAScript 2020, .mjs configuration files and @babel/cli improvements](https://github.com/docschina/babeljs.cn/tree/cn-v7/website/blog/2020-01-11-7.8.0.md)
- [ ] [7.9.0 Released: Smaller preset-env output, Typescript 3.8 support and a new JSX transform](https://github.com/docschina/babeljs.cn/tree/cn-v7/website/blog/2020-03-16-7.9.0.md)
- [ ] [7.10.0 Released: Class Fields in preset-env, '#private in' checks and better React tree-shaking](https://github.com/docschina/babeljs.cn/tree/cn-v7/website/blog/2020-05-25-7.10.0.md)
- [ ] [The State of babel-eslint](https://github.com/docschina/babeljs.cn/tree/cn-v7/website/blog/2020-07-13-the-state-of-babel-eslint.md)
- [ ] [7.11.0 Released: ECMAScript 2021 support in preset-env, TypeScript 4.0 support, printing config and the future of `babel-eslint`](https://github.com/docschina/babeljs.cn/tree/cn-v7/website/blog/2020-07-30-7.11.0.md)
- [ ] [7.12.0 Released: TypeScript 4.1, strings as import/export names, and class static blocks](https://github.com/docschina/babeljs.cn/tree/cn-v7/website/blog/2020-10-15-7.12.0.md)

**Comment by htmlin** [comment]
| Section | Title | 译者 | 完成时间 | PR |
| -- | -- | -- | -- | -- |
| Blog | 7.15.0 Released: Hack-style pipelines, TypeScript const enums and Rhino target support |  @htmlin | 2021.08.08 - 2021.08.08 | #112 |

**Comment by htmlin** [comment]
| Section | Title | 译者 | 完成时间 | PR |
| -- | -- | -- | -- | -- |
| Blog | 7.16.0 Released: ESLint 8 and TypeScript 4.5 |  @htmlin | 2021.11.21 - 2021.11.21 | #121 |
